version: "3.9"

services:
  db:
    image: "postgres:buster"
    env_file: test.env
    ports:
      - '5432:5432'
    environment:
      - CIRCLECI

  web:
    build: .
    command: bash run_dev.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: test.env
    environment:
      - CIRCLECI
      - SOCIAL_AUTH_SPOTIFY_KEY
      - SOCIAL_AUTH_SPOTIFY_SECRET      
      - DJANGO_SECRET_KEY=abc123abc123abc123abc123abc123
